const { onRequest } = require('firebase-functions/v2/https');
const { defineSecret } = require('firebase-functions/params');
const admin = require('firebase-admin');
const multer = require('multer');
const OpenAI = require('openai');
const { toFile } = require('openai/uploads');

admin.initializeApp();
const OPENAI_API_KEY = defineSecret('OPENAI_API_KEY');
const upload = multer({ storage: multer.memoryStorage(), limits: { files: 8, fileSize: 15 * 1024 * 1024 } });

const FIELD_DEFS = [
  ['process_number','Nº Processo'],['client','Cliente'],['document_type','Tipo Documento'],['transport_operation','Operação de Transporte'],['terminal_service','Serviço de Terminal?'],
  ['release_billing_date','Data de Liberação para Faturamento Processo'],['closing_date','Data de Encerramento'],['client_reference','Ref. do cliente'],['document_number','Nº Documento'],['reservation_number','Nº Reserva'],['product','Produto'],['chemical_product','Produto químico?'],
  ['shipper','Remetente'],['pickup_location','Local de Coleta'],['shipping_agency','Agência Marítima'],['customs_broker','Despachante'],['broker_reference','Ref. Despachante'],['bl_awb','Nº BL / AWB'],
  ['consignee','Destinatário'],['delivery_location','Local de Entrega'],['ship','Navio'],['voyage_number','Nº Viagem Navio'],['origin_port','Porto Origem'],['maritime_operation','Operação Marítima'],
  ['pickup_deadline','Prazo Coleta'],['delivery_deadline','Prazo Entrega'],['storage_deadline','Prazo vencimento armazenagem'],['demurrage_date','Data Demurrage'],['containerized_cargo','Carga com Container?'],['container_model','Modelo Container'],
  ['empty_return_deadline','Prev. Ret/Dev Vazio'],['empty_container_terminal','Terminal do Container Vazio'],['loading_quantity','Qtd. Carregamento'],['process_billed','Processo Faturado'],['billing_started','Faturamento Iniciado'],
  ['estimated_billing_value','Valor Previsto a Faturar'],['estimated_payment_value','Valor Previsto a Pagar'],['checklist','Checklist'],['observation','Observação'],['show_turns','Mostrar Viras?'],['route','Rota'],['storage_location','Local de Armazenagem'],
  ['generate_empty_turn','Gerar Vira Vazio'],['generate_full_turn','Gerar Vira Cheio']
];
const sourceSchema={type:'object',properties:{file_index:{type:'integer'},filename:{type:'string'},page:{type:'integer'},quote:{type:'string'},bbox:{anyOf:[{type:'object',properties:{x:{type:'number'},y:{type:'number'},width:{type:'number'},height:{type:'number'}},required:['x','y','width','height'],additionalProperties:false},{type:'null'}]}},required:['file_index','filename','page','quote','bbox'],additionalProperties:false};
const fieldSchema={type:'object',properties:{value:{anyOf:[{type:'string'},{type:'null'}]},confidence:{type:'number'},source:{anyOf:[sourceSchema,{type:'null'}]},warning:{anyOf:[{type:'string'},{type:'null'}]}},required:['value','confidence','source','warning'],additionalProperties:false};
const outputSchema={type:'object',properties:Object.fromEntries(FIELD_DEFS.map(([k])=>[k,fieldSchema])),required:FIELD_DEFS.map(([k])=>k),additionalProperties:false};
const SYSTEM_INSTRUCTION=`Você é um extrator documental para processos logísticos da COSTALOG. Preencha EXATAMENTE os campos do formulário usando SOMENTE evidências presentes nos PDFs. NUNCA invente, complete por contexto ou suponha. Se não houver evidência suficiente, value=null e confidence=0. Transcreva números, datas, códigos, nomes, valores e referências exatamente como aparecem. Leia TODOS os PDFs e faça conferência cruzada. Em conflito, não esconda o conflito: escolha apenas a evidência mais direta e explique em warning. Para perguntas booleanas use somente “Sim” ou “Não” quando houver evidência explícita; caso contrário null. Para cada campo preenchido informe arquivo, página e pequeno quote literal. Se conseguir localizar visualmente o trecho, informe bbox normalizada entre 0 e 1; se não tiver certeza, bbox=null. Nunca invente coordenadas. confidence varia de 0 a 1; >=0.95 somente com evidência muito clara. O resultado será usado em operação logística, portanto priorize precisão sobre completude.`;
function cors(req,res){const origin=req.headers.origin||'';const allowed=['https://souzarlk.github.io','https://abridor-de-processos.web.app','https://abridor-de-processos.firebaseapp.com'];if(allowed.includes(origin))res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Access-Control-Allow-Headers','Content-Type, Authorization');res.set('Access-Control-Allow-Methods','POST, OPTIONS');}
async function authenticate(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw new Error('UNAUTHENTICATED');return admin.auth().verifyIdToken(h.slice(7));}
exports.extractProcess=onRequest({region:'southamerica-east1',timeoutSeconds:540,memory:'1GiB',maxInstances:5,secrets:[OPENAI_API_KEY]},(req,res)=>{cors(req,res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({error:'Método não permitido.'});upload.array('files',8)(req,res,async err=>{if(err)return res.status(400).json({error:'Falha ao receber os PDFs: '+err.message});let remote=[];try{const user=await authenticate(req);if(!req.files?.length)return res.status(400).json({error:'Envie pelo menos um PDF.'});for(const f of req.files)if(f.mimetype!=='application/pdf')return res.status(400).json({error:`O arquivo ${f.originalname} não é PDF.`});const client=new OpenAI({apiKey:OPENAI_API_KEY.value()});const content=[{type:'input_text',text:`${SYSTEM_INSTRUCTION}\n\nARQUIVOS (file_index):\n${req.files.map((f,i)=>`${i+1}: ${f.originalname}`).join('\n')}\n\nUsuário autenticado: ${user.uid}.` }];for(const [i,f] of req.files.entries()){const up=await client.files.create({file:await toFile(f.buffer,f.originalname,{type:f.mimetype}),purpose:'user_data'});remote.push(up.id);content.push({type:'input_file',file_id:up.id});}const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-sol',input:[{role:'user',content}],text:{format:{type:'json_schema',name:'costalog_process_extraction',strict:true,schema:outputSchema}}});return res.status(200).json({fields:JSON.parse(response.output_text),meta:{model:process.env.OPENAI_MODEL||'gpt-5.6-sol',files:req.files.map(f=>f.originalname)}});}catch(e){console.error('extractProcess',e);if(e.message==='UNAUTHENTICATED')return res.status(401).json({error:'Sessão não autenticada. Faça login novamente.'});if(e?.status===401)return res.status(502).json({error:'A credencial do serviço de IA não foi aceita pelo servidor.'});if(e?.status===429)return res.status(429).json({error:'O serviço de IA está temporariamente limitado. Tente novamente.'});return res.status(500).json({error:'A extração não pôde ser validada com segurança.'});}finally{try{const c=new OpenAI({apiKey:OPENAI_API_KEY.value()});await Promise.all(remote.map(id=>c.files.delete(id).catch(()=>null)));}catch(_){}}});});
